typography_spectrum: 0.6644428058061749
color:
  brandColors:
    - '#e5e5e5'
    - '#835b4b'
    - '#a29493'
    - '#3c2824'
    - '#faaaa4'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.418617449933663
analytics:
  google: null
  facebook: null
  twitter: null
name: Margo fashion
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: children fashion
    id: e166bb47-7791-43b0-a810-89ae7d057151
    type: content
favicon: null
purpose: []
