name: Margo fashion
favicon: null
layout_spectrum: 0.418617449933663
typography_spectrum: 0.6644428058061749
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7648215137887746
  lightness: 0.8204013057984412
  saturation: 0.8203722517937422
  rhythmicContrast: 0.2854176538530737
purpose: []
